const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/contests': 'Contests',
  '/components': 'Components',
  '/charts': 'Charts',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Buttons',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/widgets': 'Widgets',
  '/gyms': "Gyms",
  '/contest/types': "Contest type",
  '/fighters': "Fighters",
  '/contest/types': "Contest type",
  '/contests/edit': 'Edit contest',
  '/contests/add': 'Create contest'
};
export default routes;
