const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/contests': 'Contests',
  '/components': 'Components',
  '/charts': 'Charts',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Buttons',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/widgets': 'Widgets',
  '/gyms': "Gyms",
  '/dictionaries/types': "Contest type",
  '/dictionaries/ranges': "Contest ranges",
  '/dictionaries/points': "Contest type points",
  '/dictionaries/levels': "Khan levels",
  '/dictionaries/suspensions': "Suspension types",
  '/fighters': "Fighters",
  '/coaches': "Coaches",
  '/judges': "Judges",
  '/contests/add': 'Create contest',
  '/contests/edit': 'Edit contest',
  '/federations/national': "Nation federations",
  '/federations/world': "World federations",
  '/federations/continental': "Continental federations",
};
export default routes;
