language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
branches:
  only:
    - master
script:
  - dotnet build IMuaythai.sln -c Release
notifications:
  email:
    on_success: never
    on_failure: always
