language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.402
branches:
    only:
        - master
script:
    - dotnet build IMuaythai.DataAccess.csproj -c Release
    - dotnet pack -c Release
    - dotnet nuget push bin/Release/IMuaythai.DataAccess.*.nupkg -k 13db7dd3-f502-4fb9-ae8a-b0b59fa1378d
     
notifications:
    email:
        on_success: never
        on_failure: always