//Login & Register
export const LOGIN_ACCOUNT_REQUEST = "LOGIN_ACCOUNT_REQUEST";
export const LOGIN_ACCOUNT_REJECTED = "LOGIN_ACCOUNT_REJECTED";
export const LOGIN_ACCOUNT_SUCCESS = "LOGIN_ACCOUNT_SUCCUESS";
export const REGISTER_ACCOUNT_REQUEST = "REGISTER_ACCOUNT_REQUEST";
export const REGISTER_ACCOUNT_REJECTED = "REGISTER_ACCOUNT_REJECTED";
export const REGISTER_ACCOUNT_SUCCESS = "REGISTER_ACCOUNT_SUCCESS";
export const CONFIRM_EMAIL_REQUEST = "CONFIRM_EMAIL_REQUEST";
export const CONFIRM_EMAIL_REJECTED = "CONFIRM_EMAIL_REJECTED";
export const CONFIRM_EMAIL_SUCCESS = "CONFIRM_EMAIL_SUCCESS";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_REJECTED = "FORGOT_PASSWORD_REJECTED";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_REJECTED = "RESET_PASSWORD_REJECTED";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const ERROR_OCCCURED = "ERROR_OCCCURED";
export const RESET_ERRORS = "RESET_ERRORS";

//Roles
export const FETCH_ROLES = "FETCH_ROLES";
export const FETCH_ROLES_FULLFILED = "FETCH_ROLES_FULLFILED";
export const FETCH_ROLES_REJECTED = "FETCH_ROLES_REJECTED";

//user roles
export const FETCH_USER_ROLES = "FETCH_USER_ROLES";
export const ADD_USER_ROLE = "ADD_USER_ROLE";
export const CANCEL_ADD_USER_ROLE = "CANCEL_ADD_USER_ROLE";
export const FETCH_USER_ROLES_FULLFILED = "FETCH_USER_ROLES_FULLFILED";
export const FETCH_USER_ROLES_REJECTED = "FETCH_USER_ROLES_REJECTED";
export const SAVE_USER_ROLE = "SAVE_USER_ROLE_REQUEST";
export const SAVE_USER_ROLE_SUCCESS = "SAVE_USER_ROLE_SUCCESS";
export const SAVE_USER_ROLE_REJECTED = "SAVE_USER_ROLE_REJECTED";

//roles requests
export const FETCH_ROLES_REQUESTS = "FETCH_ROLES_REQUESTS";
export const FETCH_ROLES_REQUESTS_FULLFILED = "FETCH_ROLES_REQUESTS_FULLFILED";
export const FETCH_ROLES_REQUESTS_REJECTED = "FETCH_ROLES_REQUESTS_REJECTED";
export const ACCEPT_ROLE_REQUEST = "ACCEPT_ROLE_REQUEST";
export const ACCEPT_ROLE_REQUEST_SUCCESS = "ACCEPT_ROLE_REQUEST_SUCCESS";
export const ACCEPT_ROLE_REQUEST_REJECTED = "ACCEPT_ROLE_REQUEST_REJECTED";
export const REJECT_ROLE_REQUEST = "REJECT_ROLE_REQUEST";
export const REJECT_ROLE_REQUEST_SUCCESS = "REJECT_ROLE_REQUEST_SUCCESS";
export const REJECT_ROLE_REQUEST_REJECTED = "REJECT_ROLE_REQUEST_REJECTED";

//Contest
export const SAVE_CONTEST_REQUEST = 'SAVE_CONTEST_REQUEST';
export const SAVE_CONTEST_SUCCESS = 'SAVE_CONTEST_SUCCESS';
export const SAVE_CONTEST_REJECTED = 'SAVE_CONTEST_REKECTED';
export const FETCH_CONTESTS_REQUEST = 'FETCH_CONTESTS_REQUEST';
export const FETCH_CONTESTS_SUCCESS = 'FETCH_CONTESTS_SUCCESS';
export const FETCH_CONTESTS_REJECTED = 'FETCH_CONTESTS_REJECTED';
